/**
 * BulbaCourses.Youtube.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SearchRequest } from './searchRequest';


export interface SearchStory { 
    id?: number;
    isHideForUser?: boolean;
    searchDate?: Date;
    userId?: string;
    searchRequest?: SearchRequest;
    searchRequestId?: number;
}
