// <auto-generated />
namespace BulbaCourses.Youtube.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_identity));
        
        string IMigrationMetadata.Id
        {
            get { return "202001091744400_added_identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
